# Generated by Django 5.0 on 2024-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='id',
        ),
        migrations.AddField(
            model_name='userauth',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
