# Generated by Django 5.0 on 2024-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_userauth_id_userauth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
